site_name: "MAGFuse"
repo_url: "https://github.com/dengdengf/test_bin"
repo_name: "GitHub"

theme:
    name: readthedocs
    highlightjs: true
    html_show_sourcelink: false
    prev_next_buttons_location: both

nav:
        - '项目总览': index.md
        - '安装': install.md
        - '用法示例': usage.md
        - '核心方法与特性': methods.md
        - '生成输入': generate.md
        - '输出说明': output.md
        - '使用 AEMB 丰度': aemb.md
        - '子命令参考': subcommands.md
        - '更新记录': whatsnew.md
        - '训练模型': training.md
        - '常见问题': faq.md
        - '半监督分箱': semi-supervised.md

